let editingId=null;
async function init(){
 if(!sb){document.getElementById("loginMsg").textContent="Add your Supabase URL and anon key to supabase-config.js first.";return}
 const {data:{session}}=await sb.auth.getSession(); setSession(session);
 sb.auth.onAuthStateChange((_e,s)=>setSession(s));
}
function setSession(session){if(session){document.getElementById("loginPanel").classList.add("hidden");document.getElementById("adminPanel").classList.remove("hidden");document.getElementById("logout").classList.remove("hidden");document.getElementById("status").textContent=session.user.email;loadTable()}else{document.getElementById("loginPanel").classList.remove("hidden");document.getElementById("adminPanel").classList.add("hidden");document.getElementById("logout").classList.add("hidden");document.getElementById("status").textContent="Not signed in"}}
async function login(e){e.preventDefault();if(!sb)return;const {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});loginMsg.textContent=error?error.message:"Signed in."}
async function logout(){await sb.auth.signOut()}
async function loadTable(){const {data,error}=await sb.from("movies").select("*").order("created_at",{ascending:false});if(error){tableWrap.innerHTML=`<p class="msg">${error.message}</p>`;return}window.movieRows=data||[];tableWrap.innerHTML=data.length?`<table class="table"><thead><tr><th>Title</th><th>Type</th><th>Year</th><th>Published</th><th></th></tr></thead><tbody>${data.map(m=>`<tr><td><b>${h(m.title)}</b><div class="muted">${h(m.genre||"")}</div></td><td>${h(m.type)}</td><td>${m.year||""}</td><td>${m.published?"Yes":"No"}</td><td><button class="smallbtn" onclick="editMovie('${m.id}')">Edit</button><button class="smallbtn danger" onclick="deleteMovie('${m.id}')">Delete</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">No movies yet. Add your first movie.</div>'}
function newMovie(){editingId=null;editorTitle.textContent="Add movie";document.querySelectorAll("#editor input").forEach(x=>{if(x.type!=="checkbox"&&x.type!=="hidden")x.value=""});year.value=new Date().getFullYear();rating.value=8;quality.value="1080p";type.value="Movie";featured.checked=false;published.checked=true;editor.classList.remove("hidden")}
function editMovie(id){const m=movieRows.find(x=>x.id===id);if(!m)return;editingId=id;editorTitle.textContent="Edit movie";title.value=m.title;year.value=m.year;type.value=m.type;genre.value=m.genre||"";rating.value=m.rating;quality.value=m.quality||"1080p";poster_url.value=m.poster_url||"";featured.checked=!!m.featured;published.checked=!!m.published;editor.classList.remove("hidden");scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
async function saveMovie(e){e.preventDefault();const payload={title:title.value.trim(),year:+year.value,type:type.value,genre:genre.value.trim(),rating:+rating.value,quality:quality.value,poster_url:poster_url.value.trim()||null,featured:featured.checked,published:published.checked};saveMsg.textContent="Saving...";let res=editingId?await sb.from("movies").update(payload).eq("id",editingId):await sb.from("movies").insert(payload);if(res.error){saveMsg.textContent=res.error.message;return}saveMsg.textContent="Saved.";closeEditor();loadTable()}
async function deleteMovie(id){if(!confirm("Delete this movie?"))return;const {error}=await sb.from("movies").delete().eq("id",id);if(error){alert(error.message);return}loadTable()}
function closeEditor(){editor.classList.add("hidden")}
function h(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
init();
